spring:
  application:
    name: Friend-Service

#  datasource:
#    url: jdbc:postgresql://localhost:5010/friend_db
#    username: "root"
#    password: "0000"
#    driver-class-name: org.postgresql.Driver
#
#  # JPA configurations
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090
