spring:
  application:
    name : User
#
#  datasource:
#    url: jdbc:postgresql://localhost:5020/user_db
#    username: "root"
#    password: "0000"
#    driver-class-name: org.postgresql.Driver
#
#    # JPA configurations
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#
#    properties:
#      hibernate:
#       dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8095

grpc:
  client:
    ledger-service:
      address: 'localhost:9095'
      negotiation-type: plaintext
    friend-service:
      address: 'localhost:9085'
      negotiation-type: plaintext
